[tasks."dev"]
description = "Run mindiff backend"
run = [
    "mise run docker",
    "mise run vault",
    "uv run uvicorn app.main:app --reload --port 8082"
]

[tasks.vault]
description = "Initialize Vault"
run = [
    "uv run python scripts/seed_vault.py"
]

[tasks.docker]
description = "Build and run Docker container"
run = [
    "cd docker && docker compose up --build --detach"
]

[tasks."sync"]
description = "Sync Python dependencies"
run = [
    "uv sync"
]

[hooks]
cd = "mise run sync"
